import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LoadingController, NavController } from '@ionic/angular';
import {NavigationOptions } from '@ionic/angular/providers/nav-controller';

@Component({
  selector: 'app-blog-list',
  templateUrl: './blog-list.page.html',
  styleUrls: ['./blog-list.page.scss'],
})
export class BlogListPage implements OnInit {

  blog=[
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/d2/9f/73/d29f730813ec7a931966ef717c9b978b.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/11/ce/5a/11ce5afea1729c5edd94edb9ebc4f07b.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/5c/9a/e6/5c9ae69b54efa6b90f908f04a3c95a0d.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/c0/40/aa/c040aae7ae8977056bdda1305fe7b7c3.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/97/59/34/9759349e941ef65042a27a09e1d4f02b.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/a7/d3/48/a7d348dc28453ec0f38127495ea1bbfb.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/21/0f/3c/210f3c8808ebd19b5b2af59bc16d6535.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/48/03/2f/48032f00a5776875866b3a3fa5949ffe.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/67/5c/29/675c29099fd59d704cade6a249a44754.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"},
    {title:'Exploitation of Healthcare workers amid CoViD crisis',src:'https://i.pinimg.com/236x/06/4b/c4/064bc4e21d731fbefc081f8c9a4d417e.jpg',desc:"<p>The Corona virus disease caused by novel Corona virus has unleashed an unbearable impact on human lives and economy. But importantly, it has unfolded the disarrayed and broken health care system of countries like Nepal and India. </p><p>Harshly privatized healthcare system is a curse to the majority citizens who have average to lower income in Asian nations. In Nepal, government hospitals have been overwhelmed by the outbreak of disease recently and private hospitals are more of profit oriented even in disasters, cutting down the pay of front-line workers, not providing them necessary protective devices and referring sick cases to other center.</p><p>Amid all the crisis, healthcare is the least affected sector but still have taken a blow. The private medical colleges who are run on support of Bulky fee from students in Nepal have been the first to neglect the safety of doctors and nurses, ignore the recommendations and guidelines and cut off the pay for Healthcare workers working front-line. In government hospitals too the Hazard compensation has not been provided. With more health personals going into quarantine, the remaining doctors have been overworked and harassed by mobs.</p>"}

  ]

  constructor(public router:Router,public navCtrl:NavController) { }

  ngOnInit() {

  }

  loadBlog(index){
    let navData: NavigationOptions = {
      queryParams: {
        data:this.blog[index]
      }
    };
    this.navCtrl.navigateForward('blog', navData)
  }
  

}
